2020-12-01 18:37:27,220 INFO    MainThread:21528 [wandb_setup.py:_flush():70] setting env: {}
2020-12-01 18:37:27,220 INFO    MainThread:21528 [wandb_setup.py:_flush():70] multiprocessing start_methods=spawn
2020-12-01 18:37:27,220 INFO    MainThread:21528 [wandb_setup.py:_flush():70] setting login settings: {}
2020-12-01 18:37:27,220 INFO    MainThread:21528 [wandb_init.py:_log_setup():303] Logging user logs to C:\Users\ST200423\PycharmProjects\SVHM\SVHNClassifier-PyTorch-master\wandb\run-20201201_183727-3cu1knua\logs\debug.log
2020-12-01 18:37:27,220 INFO    MainThread:21528 [wandb_init.py:_log_setup():304] Logging internal logs to C:\Users\ST200423\PycharmProjects\SVHM\SVHNClassifier-PyTorch-master\wandb\run-20201201_183727-3cu1knua\logs\debug-internal.log
2020-12-01 18:37:30,152 INFO    MainThread:21528 [wandb_run.py:_console_start():1218] atexit reg
2020-12-01 18:37:30,153 INFO    MainThread:21528 [wandb_run.py:_redirect():1085] redirect: SettingsConsole.WRAP
2020-12-01 18:37:30,154 INFO    MainThread:21528 [wandb_run.py:_redirect():1116] Wrapping output streams.
2020-12-01 18:37:30,154 INFO    MainThread:21528 [wandb_run.py:_redirect():1132] Redirects installed.
2020-12-01 18:37:32,941 INFO    Dummy-4   :21528 [wandb_run.py:_atexit_cleanup():1188] got exitcode: 1
2020-12-01 18:37:32,942 INFO    Dummy-4   :21528 [wandb_run.py:_restore():1160] restore
2020-12-01 18:37:32,945 INFO    Dummy-4   :21528 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "7002ef52b6b34250a55896789ffc3025"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 521
      total_bytes: 521
    }
  }
}

2020-12-01 18:37:34,948 INFO    Dummy-4   :21528 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "f752ce51b0364fbd9aad495b976babe9"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 8104
      total_bytes: 8104
    }
  }
}

2020-12-01 18:37:36,065 INFO    Dummy-4   :21528 [wandb_run.py:_show_files():1517] logging synced files
2020-12-01 18:37:36,068 INFO    Dummy-4   :21528 [internal.py:handle_exit():138] Internal process exited
