2020-12-07 08:28:55,045 INFO    MainThread:20496 [wandb_setup.py:_flush():70] setting env: {}
2020-12-07 08:28:55,046 INFO    MainThread:20496 [wandb_setup.py:_flush():70] multiprocessing start_methods=spawn
2020-12-07 08:28:55,046 INFO    MainThread:20496 [wandb_setup.py:_flush():70] setting login settings: {}
2020-12-07 08:28:55,047 INFO    MainThread:20496 [wandb_init.py:_log_setup():303] Logging user logs to C:\Users\ST200423\PycharmProjects\SVHM\SVHNClassifier-PyTorch-master\wandb\run-20201207_082855-2pcap7qj\logs\debug.log
2020-12-07 08:28:55,048 INFO    MainThread:20496 [wandb_init.py:_log_setup():304] Logging internal logs to C:\Users\ST200423\PycharmProjects\SVHM\SVHNClassifier-PyTorch-master\wandb\run-20201207_082855-2pcap7qj\logs\debug-internal.log
2020-12-07 08:28:59,255 INFO    MainThread:20496 [wandb_run.py:_console_start():1218] atexit reg
2020-12-07 08:28:59,257 INFO    MainThread:20496 [wandb_run.py:_redirect():1085] redirect: SettingsConsole.WRAP
2020-12-07 08:28:59,257 INFO    MainThread:20496 [wandb_run.py:_redirect():1116] Wrapping output streams.
2020-12-07 08:28:59,257 INFO    MainThread:20496 [wandb_run.py:_redirect():1132] Redirects installed.
2020-12-07 08:29:01,117 INFO    Dummy-4   :20496 [wandb_run.py:_atexit_cleanup():1188] got exitcode: 1
2020-12-07 08:29:01,117 INFO    Dummy-4   :20496 [wandb_run.py:_restore():1160] restore
2020-12-07 08:29:01,121 INFO    Dummy-4   :20496 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "bf80ec5d03194eda8c853cb27c93d77c"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 521
      total_bytes: 521
    }
  }
}

2020-12-07 08:29:03,125 INFO    Dummy-4   :20496 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "3ad21770cb164e239a71e37c85a22424"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 8178
      total_bytes: 8178
    }
  }
}

2020-12-07 08:29:05,131 INFO    Dummy-4   :20496 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "ccbf2c01196a47bc96a5e3057d23b772"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 8178
      total_bytes: 8178
    }
  }
}

2020-12-07 08:29:06,233 INFO    Dummy-4   :20496 [wandb_run.py:_show_files():1517] logging synced files
2020-12-07 08:29:06,235 INFO    Dummy-4   :20496 [internal.py:handle_exit():138] Internal process exited
